name: Build & Push Edge Image (GAR)

on:
  push:
    branches: [ "main" ]
    tags:
      - "v*.*.*"

permissions:
  contents: read

env:
  PROJECT_ID: consus-ems         
  REGION: europe-west2                 
  REPO: consus-edge                     # <-- your Artifact Registry repo name
  IMAGE: edge-image                     # <-- your image name in that repo

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU (multi-arch)
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GAR with service account JSON
        run: |
          echo "${{ secrets.GCP_SA_KEY }}" | docker login -u _json_key --password-stdin ${{ env.REGION }}-docker.pkg.dev

      - name: Derive image base (GAR path)
        id: img
        run: |
          echo "base=${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO }}/${{ env.IMAGE }}" >> $GITHUB_OUTPUT

      - name: Docker metadata (tags/labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ steps.img.outputs.base }}
          tags: |
            type=raw,value=main,enable={{is_default_branch}}
            type=sha,enable=true,prefix=sha-
            type=ref,event=tag
          labels: |
            org.opencontainers.image.source=${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}

      - name: Build & Push (multi-arch)
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/arm64,linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
